appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: inTbmDqQPpFEPa2T5ScmyhGvtooN/ib1S1UY5MF6PLlc69mI178dH8yRjnv/14exGp2KDlJd/2wJYrFKuXLYRN2cdUoeEZn8Rx3TDjcC1pWLCibnYHeCE0sto0bXQz190VNFBwLmeVekbzp9GW5cXbNg/BFjG15nFqRT6XW+iZx78eSgtf52v6Xaa1n9Qh87KevpZqg0MEZAQHoAebenWn/r/WVEbeWknhzDKyHc6ZhoePS9e7nVZqOiaYbuzLcIHQM8HnGdSGlRKwYEKVsWrrut+uep7qijT4MIwD73fwRQwoqaJewn5UY6n76Q6SqzT/SgkyLv2Q0JdJ8wDiFVvkhNQWd5/yREDMJbfLsM0xicozPjQPkUrwYnRkjCLf7znOmLf0jyvtISLh0z1DPevyeE13DaT7U3A7BhwGxDZt3T9ZU9AUMF9unHPeBM9QR20D51tCVTMQZJs45jExAU15jDRbBvn8QnP9U8Pqv807Cdwyssmu8W/7SBFtxZEP2e/r8TkelIe6eDB3EuXqi4irIUOsWtr/mUv4TYbvMirCEjtMN29eapum1U7rTZrFzE8ya8oZtW4IZFjDMy3odQ2sTlE7ywTbalJj/qnG90OcoL3stbHxAZNPNH9epspxoP9LdU6Gdhnp5OBOr0kpfukjteIruNT4GMbynQ+eRoClM=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
